server:
  port: 5900
spring:
  security:
    user:
      name: user
      password: password123
  application:
    name: user-consumer-ribbon-without-eureka
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: 192.168.10.30
    #如果配置了Context_path的话 配置如下路径对应
   # home-page-url-path:

user-producter:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #理论上是请求8900端口 但是还是进行了随机访问 2个微服务，原因是项目中引入了Eureka依赖
    listOfServers: localhost:8900
    #如果引入了Eureka的配置还要加入如下3行配置
#ribbon:
#  eureka:
#   enabled: false
